version: "3"

services:
  server:
    container_name: nestjs-sequelize-umzug
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

